### ISSUE TITLE
Docs: API docs with or w/o swagger

### ISSUE THREAD

**Issue by samip5** [porla/porla#177]
It would help a lot if there was a swagger API docs that would have examples of how to actually call the JSONRPC API and/or events API.

Postman collection would also help.

**Comment by vktr** [comment]
All the JSONRPC methods are documented at porla.org - for example, [`torrents.list`](https://porla.org/api/methods/torrents_list). Since it's JSONRPC I've just documented the payloads and responses and not the JSONRPC stuffs, but I should probably do some example request/responses in the top level docs for the JSONRPC API.

The events API is documented here - https://porla.org/api/events#monitoring-using-curl but should probably be expanded with an example that uses the auth token as well.

**Comment by samip5** [comment]
Yes, the issue that I encountered when looking at the docs was simply that there was no curl examples of calling any of them, which made it very hard to understand how to call them.

**Comment by vktr** [comment]
I've added an issue in the docs repo - https://github.com/porla/docs/issues/6. I'm closing this in favor of that 😃
