### ISSUE TITLE
Web UI login takes a lot of time and fails on heavy load

### ISSUE THREAD

**Issue by paxter** [porla/porla#201]
I noticed, web ui login takes a lot of time. On heavy load (long checking torrents queue) there fails something and no login is possible.

Secondly I noticed, that used memory of porla doubles on each login. I didn't take a deeper look, but it looks like, porla is forking the whole process for getting a new JWT. This would be a lot overhead and could lead to unsuspected behaviour on memory limited machines.

**Comment by vktr** [comment]
Hi!

So there's a few moving parts to this. At its essence, we use [libsodium password hashing](https://libsodium.gitbook.io/doc/password_hashing) which uses _Argon2id_. It uses a non-trivial amount of CPU cycles and memory to derive the password hashes, which is why we do that in a separate thread. I'm unsure about the specifics of `std::thread` from C++, but I don't think it forks the process.

The core issue seems to be that in a memory constrained environment, the password hashing fails since libsodium cannot allocate enough memory. Perhaps it would be advisable to make the `memlimit` parameter configurable - since the libsodium docs mention this,

> There is no "insecure" value for memlimit, though the more memory, the better.

We can keep the default as-is and just make it overridable from the configuration.

Thoughts?

**Comment by vktr** [comment]
We should also be able to implement [server relief](https://libsodium.gitbook.io/doc/password_hashing#server-relief)

**Comment by paxter** [comment]
Well, might be all right. But doubling the memory (in my case from 700M to 1,5G) for just creating a simple JWT is insane.

**Comment by paxter** [comment]
I'm not familiar with libsodium, so I've no opinion about the memlimit. But in general creating a new JWT should be below 1 second and shouldn't take the same memory as the main process.

**Comment by paxter** [comment]
Otherwise it would be better to look for another solution and don't use libsodium if it's to complicated.

**Comment by vktr** [comment]
I agree - the default limit that libsodium uses (and we) for what they call sensitive is ~1gb. So the numbers you see makes sense. I wasn't aware of this and I haven't ran into any issues with it since I haven't really tested in a memory constrained environment, but I can see why it's an issue 😃 

Changing to the minimum limit they have documented (~8kb) both reduces the memory usage by a factor of a lot, and also makes issuing a JWT much much faster. A win I would say.

I'll put up a pull request for this later tonight!

**Comment by paxter** [comment]
That sounds all fine. Thanks for checking and investigating.

I started to use Porla in my prod environment. It's by far the best client I've ever tested although it's still in beta. :)

**Comment by vktr** [comment]
Of course, and I'm happy to hear!

**Comment by vktr** [comment]
The memlimit is now configurable and also defaults to the minimum value. Since it is stored as a part of the password hash, you need to recreate your user account in Porla.

Just do `sqlite3 /path/to/porla.sqlite "delete from users"` then refresh the web UI and you will end up at the setup page again.

**Comment by paxter** [comment]
Just tested with your fix and it works like a charm.
No memory increasing anymore and web ui login is very fast now. :)

Good job and thanks as usual for fast fixing.
