### ISSUE TITLE
[0x00007f43462d5a60] [error]   Out of memory when hashing password

### ISSUE THREAD

**Issue by omgbox** [porla/porla#263]
ubuntu 22.04 / 64bit KVM
20gb
1GB

unable to generate password.

**Comment by vktr** [comment]
Hi! This was fixed a while back -  if you remove the user from the `users` table and set up a new user account, it should use less memory since the defaults have been changed (but older accounts do not take this into account).

Something like,

`sqlite3 porla.sqlite 'delete from users'`

And then go through the setup again.

**Comment by vktr** [comment]
Also, "fixed" in this case means that it is fixed in the latest beta version. So use the artifacts from this build - https://github.com/porla/porla/actions/runs/6058028656

**Comment by vktr** [comment]
Closing this since it is fixed but not released - please reach out again if the problem persists in the latest beta!
